@echo off
cd /d C:\Users\jbuck\arsenal-analytics
call conda activate base
echo Scraping Arsenal PL...
python pipeline/scrape_and_load.py --league "ENG-Premier League" --season 2526 --team Arsenal
echo Scraping Arsenal UCL...
python pipeline/scrape_and_load.py --league "INT-Champions League" --season 2526 --team Arsenal
echo Scraping Arsenal FA Cup...
python pipeline/scrape_and_load.py --league "ENG-FA Cup" --season 2526 --team Arsenal
echo Scraping Arsenal League Cup...
python pipeline/scrape_and_load.py --league "ENG-League Cup" --season 2526 --team Arsenal
echo Scraping LAFC MLS...
python pipeline/scrape_and_load.py --league "USA-MLS" --season 2627 --team "Los Angeles FC"
echo All done!
pause
