-- Read-only schema capture apart from the private export buffer it creates.
-- Download public._schema_baseline_export in seq order, then drop it.
drop table if exists public._schema_baseline_export;
create table public._schema_baseline_export(
  seq bigint generated always as identity primary key,
  section text not null,
  ddl text not null
);
revoke all on public._schema_baseline_export from public,anon,authenticated;
grant select,delete on public._schema_baseline_export to service_role;

do $capture$
declare r record; cols text; opts text; payload text; kind text; added integer; next_ord integer:=0;
begin
  create temporary table baseline_rel_order(oid oid primary key,ord integer not null) on commit drop;
  loop
    insert into baseline_rel_order(oid,ord)
    select c.oid,next_ord
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relkind in('v','m')
      and not exists(select 1 from baseline_rel_order done where done.oid=c.oid)
      and not exists(
        select 1 from pg_rewrite rw join pg_depend d on d.classid='pg_rewrite'::regclass and d.objid=rw.oid
        join pg_class dep on dep.oid=d.refobjid join pg_namespace dn on dn.oid=dep.relnamespace
        where rw.ev_class=c.oid and d.refobjid<>c.oid and dn.nspname='public' and dep.relkind in('v','m')
          and not exists(select 1 from baseline_rel_order ready where ready.oid=dep.oid)
      );
    get diagnostics added=row_count;
    exit when added=0;
    next_ord:=next_ord+1;
  end loop;
  if (select count(*) from baseline_rel_order)<>(select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in('v','m')) then
    raise exception 'could not topologically order public views';
  end if;
  insert into public._schema_baseline_export(section,ddl) values
  ('preamble',$ddl$-- Canonical production-schema baseline, generated from PostgreSQL catalogs.
begin;
do $roles$ begin
  if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin; end if;
  if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin; end if;
  if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role nologin; end if;
end $roles$;
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm;
create extension if not exists unaccent;
$ddl$);

  for r in
    select n.nspname,t.typname,string_agg(quote_literal(e.enumlabel),',' order by e.enumsortorder) labels
    from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid
    where n.nspname='public' group by n.nspname,t.typname order by t.typname
  loop
    insert into public._schema_baseline_export(section,ddl)
    values('types',format('create type %I.%I as enum (%s);',r.nspname,r.typname,r.labels));
  end loop;

  for r in
    select c.oid,c.relname,s.seqstart,s.seqincrement,s.seqmin,s.seqmax,s.seqcache,s.seqcycle
    from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_sequence s on s.seqrelid=c.oid
    where n.nspname='public' order by c.relname
  loop
    insert into public._schema_baseline_export(section,ddl) values('sequences',format(
      'create sequence public.%I start with %s increment by %s minvalue %s maxvalue %s cache %s %s;',
      r.relname,r.seqstart,r.seqincrement,r.seqmin,r.seqmax,r.seqcache,case when r.seqcycle then 'cycle' else 'no cycle' end));
  end loop;

  for r in
    select c.oid,c.relname,c.relrowsecurity,c.relforcerowsecurity,c.reloptions
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relkind in('r','p') and c.relname<>'_schema_baseline_export'
    order by c.relname
  loop
    select string_agg(
      format('%I %s%s%s%s',a.attname,format_type(a.atttypid,a.atttypmod),
        case a.attidentity when 'a' then ' generated always as identity' when 'd' then ' generated by default as identity' else '' end,
        case when a.attgenerated<>'' then format(' generated always as (%s) stored',pg_get_expr(ad.adbin,ad.adrelid))
             when ad.adbin is not null and a.attidentity='' then format(' default %s',pg_get_expr(ad.adbin,ad.adrelid)) else '' end,
        case when a.attnotnull then ' not null' else '' end),E',\n  ' order by a.attnum)
    into cols
    from pg_attribute a left join pg_attrdef ad on ad.adrelid=a.attrelid and ad.adnum=a.attnum
    where a.attrelid=r.oid and a.attnum>0 and not a.attisdropped;
    insert into public._schema_baseline_export(section,ddl)
    values('tables',format('create table public.%I (\n  %s\n)%s;',r.relname,cols,
      case when r.reloptions is null then '' else format(' with (%s)',array_to_string(r.reloptions,',')) end));
    if r.relrowsecurity then insert into public._schema_baseline_export(section,ddl) values('rls',format('alter table public.%I enable row level security;',r.relname)); end if;
    if r.relforcerowsecurity then insert into public._schema_baseline_export(section,ddl) values('rls',format('alter table public.%I force row level security;',r.relname)); end if;
  end loop;

  for r in
    select conrelid::regclass::text rel,conname,pg_get_constraintdef(oid,true) def
    from pg_constraint where connamespace='public'::regnamespace and contype in('p','u','c','x','f')
    order by case contype when 'f' then 2 else 1 end,conrelid::regclass::text,conname
  loop
    insert into public._schema_baseline_export(section,ddl)
    values('constraints',format('alter table %s add constraint %I %s;',r.rel,r.conname,r.def));
  end loop;

  -- Temporary signatures allow views to bind to functions before their full
  -- bodies (which may themselves reference views) are restored.
  for r in
    select p.oid,n.nspname,p.proname,p.proretset,p.prorettype,
      pg_get_function_identity_arguments(p.oid) args,pg_get_function_result(p.oid) result
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.prokind='f'
      and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')
    order by p.proname,p.oid
  loop
    insert into public._schema_baseline_export(section,ddl) values('function_stubs',format(
      'create function public.%I(%s) returns %s language plpgsql as $stub$ begin %s end $stub$;',
      r.proname,r.args,r.result,
      case when r.prorettype='trigger'::regtype then 'return new;'
           when r.proretset or r.prorettype='void'::regtype then 'return;'
           else 'return null;' end));
  end loop;

  for r in
    select c.oid,c.relname,c.relkind,c.reloptions,o.ord
    from pg_class c join pg_namespace n on n.oid=c.relnamespace join baseline_rel_order o on o.oid=c.oid
    order by o.ord,c.relname
  loop
    if r.relkind='v' then
      insert into public._schema_baseline_export(section,ddl)
      values('relations',format('create view public.%I as %s;',r.relname,pg_get_viewdef(r.oid,true)));
      if r.reloptions is not null then insert into public._schema_baseline_export(section,ddl)
        values('relation_options',format('alter view public.%I set (%s);',r.relname,array_to_string(r.reloptions,','))); end if;
    else
      insert into public._schema_baseline_export(section,ddl)
      values('relations',format('create materialized view public.%I as %s with no data;',r.relname,pg_get_viewdef(r.oid,true)));
      if r.reloptions is not null then insert into public._schema_baseline_export(section,ddl)
        values('relation_options',format('alter materialized view public.%I set (%s);',r.relname,array_to_string(r.reloptions,','))); end if;
    end if;
  end loop;

  for r in
    select pg_get_functiondef(p.oid) def
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.prokind='f'
      and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')
    order by p.proname,p.oid
  loop insert into public._schema_baseline_export(section,ddl) values('functions',r.def||';'); end loop;

  for r in
    select indexdef from pg_indexes where schemaname='public' and tablename<>'_schema_baseline_export'
    order by tablename,indexname
  loop insert into public._schema_baseline_export(section,ddl) values('indexes',r.indexdef||';'); end loop;

  for r in
    select pg_get_triggerdef(t.oid,true) def from pg_trigger t
    join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and not t.tgisinternal order by c.relname,t.tgname
  loop insert into public._schema_baseline_export(section,ddl) values('triggers',r.def||';'); end loop;

  for r in
    select c.relname,p.polname,p.polpermissive,p.polroles,p.polcmd,
      pg_get_expr(p.polqual,p.polrelid) qual,pg_get_expr(p.polwithcheck,p.polrelid) chk
    from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' order by c.relname,p.polname
  loop
    insert into public._schema_baseline_export(section,ddl) values('policies',format(
      'create policy %I on public.%I as %s for %s to %s%s%s;',r.polname,r.relname,
      case when r.polpermissive then 'permissive' else 'restrictive' end,
      case r.polcmd when 'r' then 'select' when 'a' then 'insert' when 'w' then 'update' when 'd' then 'delete' else 'all' end,
      (select string_agg(case when x=0 then 'public' else quote_ident(pg_get_userbyid(x)) end,',') from unnest(r.polroles) x),
      case when r.qual is null then '' else format(' using (%s)',r.qual) end,
      case when r.chk is null then '' else format(' with check (%s)',r.chk) end));
  end loop;

  for r in
    select c.relname,c.relkind,coalesce(g.rolname,'PUBLIC') grantee,string_agg(a.privilege_type,',' order by a.privilege_type) privileges
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    cross join lateral aclexplode(c.relacl) a
    left join pg_roles g on g.oid=a.grantee
    where n.nspname='public' and c.relname<>'_schema_baseline_export'
    group by c.relname,c.relkind,g.rolname order by c.relname,g.rolname
  loop
    kind:=case when r.relkind='S' then 'sequence' else 'table' end;
    insert into public._schema_baseline_export(section,ddl)
    values('grants',format('grant %s on %s public.%I to %I;',r.privileges,kind,r.relname,r.grantee));
  end loop;

  for r in
    select p.oid::regprocedure::text identity,coalesce(g.rolname,'PUBLIC') grantee,
      string_agg(a.privilege_type,',' order by a.privilege_type) privileges
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(p.proacl) a
    left join pg_roles g on g.oid=a.grantee where n.nspname='public'
    group by p.oid,g.rolname order by identity,grantee
  loop insert into public._schema_baseline_export(section,ddl)
    values('grants',format('grant %s on function %s to %I;',r.privileges,r.identity,r.grantee)); end loop;

  for r in select unnest(array[
    'detector_priority','detector_requirements','invariants','league_mart_entry_objects','leagues',
    'metric_catalog','metric_defs','metric_synonyms','pillar_defs','pool_metric_relevance',
    'role_pillar_weights','team_metric_defs','team_names','xt_grid','analytics_publication_probe'
  ]) relname loop
    execute format('select jsonb_agg(to_jsonb(t))::text from public.%I t',r.relname) into payload;
    if payload is not null then insert into public._schema_baseline_export(section,ddl) values('seed',format(
      'insert into public.%I select * from jsonb_populate_recordset(null::public.%I,$seed$%s$seed$::jsonb);',
      r.relname,r.relname,payload)); end if;
  end loop;

  insert into public._schema_baseline_export(section,ddl) values
  ('finish','commit;');
end $capture$;
