const {chromium}=require('C:/Users/jbuck/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const results=[];fs.mkdirSync('artifacts/ux-audit',{recursive:true});
for(const theme of ['light','dark']){
 const c=await browser.newContext({viewport:{width:1440,height:900}});await c.addInitScript(t=>localStorage.setItem('theme',t),theme);
 await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='127.0.0.1')return r.continue();const lib=u.pathname.split('/').pop();if(['html2canvas.min.js','jspdf.umd.min.js'].includes(lib))return r.fulfill({path:'artifacts/ux-audit-writing/vendor/'+lib,contentType:'application/javascript'});if(u.pathname.includes('/rest/v1/'))return r.fulfill({json:[]});return r.abort();});
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765/match.html');await p.waitForTimeout(500);
 await p.evaluate(()=>{
  TEAMS.__ALL__={name:'__ALL__',display:'All teams',color:'#1256a3',comps:[]};TEAMS.Seattle={name:'Seattle',display:'Seattle',color:'#1256a3',comps:[]};TEAMS.Kansas={name:'Kansas',display:'Kansas',color:'#a32145',comps:[]};MATCH2EV['Seattle Sounders FC']='Seattle';MATCH2EV['Kansas City']='Kansas';
  S.team='__ALL__';S.matchTeams=['Seattle','Kansas'];S.viewTeam='Seattle';S.oppTeam='Kansas';S.selMatch=1;S.matches=[{game_id:1,home_team:'Seattle Sounders FC',away_team:'Kansas City',home_score:2,away_score:1,date:'2026-09-01',competition:'Synthetic fixture'}];
  S.events=[];for(let i=0;i<40;i++){const team=i%2?'Kansas':'Seattle',player=i%4<2?'Alex Roldan':'Cristian Roldan';S.events.push({game_id:1,team,player,type:i%5===0?'SavedShot':'Pass',is_shot:i%5===0,is_goal:false,is_open_play:true,x:20+i,y:30+i%30,end_x:80+i%10,end_y:50,minute:i+1,period:1,second:0,outcome_type:'Successful',xg:i%10===0?null:.3});}S.starters=new Set(['Alex Roldan','Cristian Roldan']);S.playerPos={'Alex Roldan':'MC','Cristian Roldan':'FW'};S.carries=[{team:'Seattle',start_x:30,start_y:50,end_x:85,end_y:50,minute:15,period:1}];S.carriesAvailable=true;S.periods=new Set(['1']);S.timeFilter={s:10,e:30};S.outcomes=new Set();S.selPlayer='Alex Roldan';
 });
 const plots=['passes','progressive','final_third','zone14','box_passes','keypasses','network','combos','shots','heatmap','xt','xt_carry','defensive','pressure','shape','formation','dominance'];
 for(const plot of plots){await p.evaluate(v=>{S.activeVizs=[v];renderAll();},plot);assert.equal(await p.locator('.pitch-canvas').count(),1,plot);await p.locator('.plot-data summary').click();await p.locator('.plot-data table').waitFor();results.push({theme,plot,canvas:true,exactTable:true});}
 await p.evaluate(()=>{S.activeVizs=['network'];S.compareMode=true;renderAll();buildTimeline();renderMomentumTab();});assert(!(await p.locator('.pitch-area').innerText()).includes('__ALL__'));assert(!(await p.locator('#momWrap').innerText()).includes('__ALL__'));
 await p.screenshot({path:`artifacts/ux-audit/match-synthetic-${theme}.png`});
 const matchURL=await p.evaluate(()=>{S.activeVizs=['passes'];S.compareMode=false;renderAll();return location.href;});await p.evaluate(url=>{S.activeVizs=['shots'];S.timeFilter=null;restoringMatchURL=true;restoreMatchURL(new URL(url).searchParams);restoringMatchURL=false;},matchURL);assert.equal(await p.evaluate(()=>S.activeVizs[0]),'passes');assert.equal(await p.evaluate(()=>S.timeFilter.s),10);
 await p.evaluate(()=>{S.activeVizs=['network'];renderAll();});for(const format of ['PNG','PDF']){const download=p.waitForEvent('download');await p.evaluate(f=>window['download'+f](document.querySelector('.pitch-canvas'),'Pass Network'),format);await(await download).saveAs(`artifacts/ux-audit/match-download-${theme}.${format.toLowerCase()}`);results.push({theme,matchDownload:format});}
 for(const width of [320,375,390,640,768,1024,1440,1920]){await p.setViewportSize({width,height:900});assert(await p.locator('#hdrTabs').isVisible());results.push({theme,width,matchTabs:true});}
 await p.evaluate(()=>{S.selPlayer='Alex Roldan';S.cmpPlayer='Cristian Roldan';showComparison();});await p.waitForTimeout(50);assert(await p.locator('#cmpClose').evaluate(el=>document.activeElement===el));await p.keyboard.press('Escape');assert(!(await p.locator('#cmpOverlay').getAttribute('class')).includes('show'));
 await p.goto('http://127.0.0.1:8765/teams.html');await p.waitForTimeout(300);
 await p.evaluate(async()=>{TEAMS=[{team:'A',matches:6},{team:'B',matches:6}];SEL='A';TAB='Maps';LG='ALL';MP.kind='against';
   const against=MAPS.find(m=>/against|conced/i.test(m.k+' '+m.l));MP.kind=against.k;
   sbAll=async table=>table==='mv_team_match'?[{game_id:1}]:table==='v_team_shots'?[{game_id:1,team:'B',player:'One',x:90,y:50,xg:0,outcome:'off'},{game_id:1,team:'B',player:'Two',x:91,y:51,xg:null,outcome:'saved'},{game_id:1,team:'B',player:'Three',x:92,y:52,xg:.3,outcome:'goal',is_goal:true}]:[];
   await draw();});
 const text=await p.locator('#main').innerText();assert(text.includes('0.30'));assert(text.includes('2/3 shots covered'));assert(text.includes('1 eligible fixtures'));
 await p.screenshot({path:`artifacts/ux-audit/teams-conceded-synthetic-${theme}.png`});
 await p.evaluate(async()=>{let release;sbAll=()=>new Promise(resolve=>release=resolve);TAB='Matches';const pending=draw();TAB='Profile';SEL='B';draw();release([]);await pending;});assert(!(await p.locator('#main').innerText()).includes('Match-by-match style'));
 await p.setViewportSize({width:1440,height:900});await p.evaluate(async()=>{SEL='A';TAB='Squad';sbAll=async table=>table==='mv_player_season'?Array.from({length:50},(_,i)=>({player_id:i+1,player_name:'Synthetic squad player '+String(i+1).padStart(2,'0'),nineties:50-i,minutes:4500-i*90,starts:50-i})):[];await draw();});assert.equal(await p.locator('#main tbody tr').count(),50);
 for(const format of ['PNG','PDF']){const download=p.waitForEvent('download');await p.evaluate(f=>window['export'+f](),format);await(await download).saveAs(`artifacts/ux-audit/squad-download-${theme}.${format.toLowerCase()}`);results.push({theme,squadDownload:format,rows:50});}
 await p.evaluate(()=>{TAB='Profile';draw();});await p.goBack();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>TAB),'Squad');assert.equal(await p.locator('#main tbody tr').count(),50);results.push({theme,teamBrowserBack:true,matchURLRestoration:true});
 await p.setViewportSize({width:640,height:900});await p.evaluate(()=>document.documentElement.style.zoom='2');await p.screenshot({path:`artifacts/ux-audit/teams-200percent-${theme}.png`});assert(await p.locator('#main tbody tr').last().count());
 results.push({theme,teamConcededKnownXg:true,teamStaleResponse:true,errors});await c.close();
}
await browser.close();fs.writeFileSync('artifacts/ux-audit/match-teams-browser.json',JSON.stringify(results,null,2));const errors=results.flatMap(x=>x.errors||[]);console.log(JSON.stringify({checks:results.length,errors},null,2));assert.equal(errors.length,0);})().catch(e=>{console.error(e);process.exit(1)});
