// Exact current page scripts in a browser. All external traffic is blocked.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('C:/Users/jbuck/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'artifacts/ux-audit-post-verification');fs.mkdirSync(out,{recursive:true});
const checks=[];function check(name,value){assert.ok(value,name);checks.push(name);console.log('PASS '+name)}
(async()=>{const server=http.createServer((req,res)=>{const f=path.join(root,'dashboard',new URL(req.url,'http://localhost').pathname);if(!f.startsWith(path.join(root,'dashboard'))||!fs.existsSync(f)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css');res.end(fs.readFileSync(f))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({channel:'msedge',headless:true});
try{const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>{if(r.request().url().startsWith(base))return r.continue();if(r.request().url().includes('/rest/v1/'))return r.fulfill({json:[]});return r.abort()});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/writing-lab.html');await page.waitForTimeout(100);
const writing=await page.evaluate(async()=>{
 const a={id:'a',game_id:'101',competition:'ENG-Premier League',season:'2627',home_team:'Alpha',away_team:'Beta',scrape_status:'ready',workflow_status:'working',workspace_notes:'original',whoscored_url:'https://www.whoscored.com/Matches/101'},b={...a,id:'b',game_id:'102',scrape_status:'queued'};
 PROJECTS=[a,b];const events=[{ws_id:1,team:'Alpha',type:'Pass',is_touch:true,x:70,y:50,end_x:90,end_y:50,outcome_type:'Successful'}];let release;sbAll=()=>new Promise(r=>release=r);
 const first=openProject('a');await openProject('b');const second=openProject('a');release(events);await Promise.all([first,second]);const reentry=CUR.id==='a'&&EVENTS.length===1&&document.querySelector('.pitch')!==null;
 let oldResponse;api=()=>new Promise(r=>oldResponse=r);const oldPoll=loadProjects(true);CUR.workspace_notes='successfully saved';queueSave();clearTimeout(saveTimers.get('a'));api=async(path,opt)=>[{...a,...JSON.parse(opt.body)}];await saveProject('a');oldResponse([{...a},b]);await oldPoll;const saved=CUR.workspace_notes==='successfully saved';
 window.fetch=async()=>({ok:true,json:async()=>({content:[{text:'new generated brief'}]})});await generateBrief(true);CUR.workspace_notes='note before debounce';queueSave();clearTimeout(saveTimers.get('a'));const brief=CUR.editorial_brief==='new generated brief'&&drafts.get('a').payload.editorial_brief==='new generated brief';
 const fingerprint=briefFingerprint();evidenceStates.get('a').events[0].end_x=95;const contentVersion=briefFingerprint()!==fingerprint;
 const store=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw Error('denied')};api=async()=>{throw Error('offline')};CUR.workspace_notes='unsaved recovery';queueSave();clearTimeout(saveTimers.get('a'));await saveProject('a');const storage=/local recovery failed/.test(document.getElementById('saveState').textContent)&&!/retained locally/.test(document.getElementById('saveState').textContent);Storage.prototype.setItem=store;
 const retained=EVENTS;EVENTS=[{...events[0],player:'Same name',player_id:1},{...events[0],ws_id:2,player:'Same name',player_id:2}];TEAM='Alpha';PLAYER='id:2';VIZ='passes';const identity=selectedPlotEvents().length===1&&selectedPlotEvents()[0].player_id===2;EVENTS=retained;PLAYER='ALL';
 stopPolling();return {reentry,saved,brief,contentVersion,storage,identity};
});for(const[k,v]of Object.entries(writing))check('Writing '+k,v);await page.screenshot({path:path.join(out,'writing-recovery.png')});
await page.goto(base+'/match.html');await page.waitForTimeout(100);
const match=await page.evaluate(async()=>{
 TEAMS.__ALL__={name:'__ALL__',comps:[{v:'TEST'}],color:'#000'};TEAMS.Alpha={name:'Alpha',comps:[{v:'TEST'}],color:'#000'};TEAMS.Beta={name:'Beta',comps:[{v:'TEST'}],color:'#000'};S.team='__ALL__';S.viewTeam='Alpha';S.starters=new Set(['Starter']);S.playerPos={Starter:'MC'};S.events=[{team:'Alpha',player:'Starter',type:'Pass',x:30,y:50,period:1,minute:1,second:0,outcome_type:'Successful'},{team:'Alpha',player:'Sub',type:'Pass',x:50,y:50,period:1,minute:1,second:1,outcome_type:'Successful'}];const canvas=document.createElement('canvas');canvas.width=600;canvas.height=500;const title=document.createElement('div'),legend=document.createElement('div');let membership=[];for(const entry of ['__ALL__','Alpha','Beta']){S.team=entry;renderNetwork(canvas.getContext('2d'),canvas,S.events,title,legend,null);membership.push(S.canvasEvents.get(canvas).map(x=>x.player).join(','))}
 const network=membership.every(x=>x==='Starter')&&legend.textContent==='Starters only';
 let old;sbAll=()=>new Promise(r=>old=r);S.team='Alpha';const slow=loadMatches();S.team='Beta';sbAll=async()=>[{game_id:'new',date:'2026-10-01'}];const originalRender=renderMatchSelect;renderMatchSelect=()=>{};await loadMatches();old([{game_id:'old',date:'2026-10-01'}]);await slow;const list=S.matches[0].game_id==='new';renderMatchSelect=originalRender;
 history.replaceState({},'','?game=999999');sbAll=async()=>[];await openDeepLink();const notFound=/Match not found/.test(document.getElementById('pitchArea').textContent);return{network,list,notFound};
});for(const[k,v]of Object.entries(match))check('Match '+k,v);
await page.goto(base+'/players.html');await page.waitForTimeout(100);
const player=await page.evaluate(async()=>{
 PLAYERS=[{player_id:'1',player_name:'Synthetic',team:'Test',pool:'W',nineties:5}];PLG.Test='TEST';PLEAGUES=[{league:'TEST'}];WEIGHTS={W:{}};DEFS=[{key:'key_pass_90',label:'Key passes',unit:'per 90',grp:'Creation'}];PLGSCOPE='ALL';SEL='1';EVIDENCE_PID=null;fillTeamSel();const events=[{game_id:'10',type:'Pass',ok:true,is_open_play:true,x:30,y:40,end_x:90,end_y:50,keypass:true}];sbAll=async()=>[{metric:'key_pass_90',value:2,pct:70}];let resolve;loadEvidenceLayers=()=>new Promise(r=>resolve=r);
 const state={v:1,tab:'Plot studio',player:'1',league:'ALL',evidence:{game:'10'},studio:{mode:'events',metrics:['key_pass_90'],layers:['pass','key'],pattern:false,group:'Creation'}};history.replaceState({},'','?state='+encodeURIComponent(JSON.stringify(state)));const restoring=restorePlayerState();await Promise.resolve();resolve({actions:events,carries:[],receipts:[],contextReady:true});await restoring;const cold=TAB==='Plot studio'&&PB.mode==='events'&&PB.metrics.join(',')==='key_pass_90'&&PB.layers.join(',')==='pass,key'&&EVF.game==='10'&&PB.pattern===false;
 const missing=nullableMetric(null)===null&&nullableMetric('')===null&&nullableMetric(0)===0&&tier(null).c==='var(--text3)';
 return {cold,missing};
});for(const[k,v]of Object.entries(player))check('Player '+k,v);await page.screenshot({path:path.join(out,'studio-restored.png'),fullPage:true});
const additional=await page.evaluate(async()=>{
 DEFS=Array.from({length:3},(_,i)=>({key:'metric'+i,label:'Measure '+i,unit:'per 90',grp:'Creation'}));PMCACHE=Object.fromEntries(DEFS.map(d=>[d.key,{value:1,pct:60}]));
 let resolve;loadEvidenceLayers=()=>new Promise(r=>resolve=r);sbAll=async()=>[];const pending=drillFor('2','key_pass_90');openCategoryPizza('Creation');const before=document.getElementById('drillBody').innerHTML;resolve({actions:[],carries:[],receipts:[],contextReady:true});await pending;
 const modal=document.getElementById('drillBody').innerHTML===before&&before.includes('Creation');closeDrill();EVF.game='wrong-fixture';TAB='Player';GRP='Combined';const ctx=futScoutExportContext(document.getElementById('main'));const exportScope=!JSON.stringify(ctx).includes('wrong-fixture')&&ctx.eventFilters.scope.includes('all loaded');
 history.replaceState({},'','?state='+encodeURIComponent(JSON.stringify({v:1,tab:'Scout',league:'ALL',scout:{pool:'W',metrics:[],show:'val',sort:{col:'player',dir:1}}})));await restorePlayerState();const scout=SK.show==='val'&&SK.sort.col==='player'&&SK.sort.dir===1;
 history.replaceState({},'','/players.html');await restorePlayerState();const defaults=TAB==='Player'&&EVF.game===''&&PLGSCOPE==='ALL';return{modal,exportScope,scout,defaults};
});for(const[k,v]of Object.entries(additional))check('Player '+k,v);
await page.goto(base+'/quick-ingest.html');await page.waitForTimeout(100);
const ingestion=await page.evaluate(async()=>{
 clearTimeout(timer);let resolve,payload,path;api=()=>new Promise(r=>resolve=r);keyHash=async()=>'synthetic-local-only';$('matchUrl').value='https://www.whoscored.com/Matches/101';const initialCompetition=$('competition').value,initialSeason=$('season').value;const operation=submit({preventDefault(){}});
 $('matchUrl').value='https://www.whoscored.com/Matches/202';$('competition').selectedIndex=1;api=async(p,opt)=>{if(opt?.method==='POST'){payload=JSON.parse(opt.body);return[{id:'a',scrape_status:'queued'}]}return[]};resolve([]);await operation;
 const snapshot=payload.game_id==='101'&&payload.competition===initialCompetition&&payload.season===initialSeason;const preserved=$('matchUrl').value.endsWith('/202');
 rowsCache=[{id:'a',scrape_status:'error'}];api=async(p,opt)=>{path=p;return[]};await retry('a');const retryRejected=path.includes('scrape_status=eq.error')&&$('feedback').textContent.includes('Retry failed');clearTimeout(timer);return{snapshot,preserved,retryRejected};
});for(const[k,v]of Object.entries(ingestion))check('Ingestion '+k,v);
const snapshotExport=await page.evaluate(async()=>{
 const card=document.createElement('section');card.innerHTML='<h2>Original subject</h2>';card.dataset.exportContext=JSON.stringify({subject:'Original subject',filters:'original filter'});document.body.appendChild(card);let captured='';window.html2canvas=async stage=>{captured=stage.textContent;const c=document.createElement('canvas');c.width=100;c.height=100;return c};const click=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){};
 const oldUrl=location.href;const pending=FutScoutExports.capture(card,'png');card.textContent='New subject';card.dataset.exportContext=JSON.stringify({subject:'New subject',filters:'new filter'});history.replaceState({},'','?changed=after-export');await pending;HTMLAnchorElement.prototype.click=click;card.remove();return captured.includes('Original subject')&&captured.includes('original filter')&&captured.includes(oldUrl)&&!captured.includes('New subject')&&!captured.includes('changed=after-export');
});check('Export captures content/context/URL before asynchronous rendering',snapshotExport);
await page.goto(base+'/search.html');await page.waitForTimeout(100);
for(const mode of ['absent','denied']){
 await page.evaluate(mode=>{shortlistRows=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:mode==='absent'?undefined:{writeText:async()=>{throw Error('denied')}}})},mode);
 const downloading=page.waitForEvent('download');await page.locator('#copy').click();const download=await downloading;const file=path.join(out,'clipboard-'+mode+'.tsv');await download.saveAs(file);check('Clipboard '+mode+' downloads contextual TSV',fs.readFileSync(file,'utf8').includes('Filters:'));
}
check('No browser script exceptions',errors.length===0);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,boundary:'Local exact-source scripts; external requests blocked; no production writes.'},null,2));
}finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
