/* Local-only browser fixtures. Every non-local request is intercepted; no production writes. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/jbuck/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'artifacts','ux-audit-writing');fs.mkdirSync(out,{recursive:true});
const projects=[{id:'00000000-0000-4000-8000-000000000001',game_id:'101',competition:'ENG-Premier League',season:'2627',home_team:'Alpha United',away_team:'Beta Town',home_score:1,away_score:0,scrape_status:'ready',workflow_status:'working',workspace_notes:'',article_draft:'',whoscored_url:'https://www.whoscored.com/Matches/101',updated_at:'2026-10-02T12:00:00Z'}, {id:'00000000-0000-4000-8000-000000000002',game_id:'102',competition:'ENG-League Cup',season:'2627',home_team:'Gamma',away_team:'Delta',scrape_status:'queued',workflow_status:'working',workspace_notes:'',article_draft:'',whoscored_url:'https://www.whoscored.com/Matches/102',updated_at:'2026-10-02T12:00:00Z'}];
const events=[{game_id:'101',ws_id:1,period:1,minute:4,second:3,team:'Alpha United',player_id:10,player:'Alex Long-Name',type:'Pass',outcome_type:'Successful',x:30,y:40,end_x:75,end_y:50,is_touch:true},{game_id:'101',ws_id:2,period:1,minute:5,second:2,team:'Beta Town',player_id:20,player:'Beth',type:'SavedShot',outcome_type:'Unsuccessful',x:85,y:45,is_shot:true,is_touch:true}];
let patchDelay=0,patchFailure=false,posts=0,patches=[],eventFailure=false,briefDelay=0,eventEmpty=false,queueFailure=false,briefFailure=false;
const errors=[],checks=[];const check=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS '+name)};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function savePlot(page,format,name){const pending=page.waitForEvent('download',{timeout:15000});await page.getByRole('button',{name:'Plot '+format.toUpperCase(),exact:true}).click();await(await pending).saveAs(path.join(out,name));check(name+' actual download',fs.statSync(path.join(out,name)).size>1000)}
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,'dashboard',new URL(req.url,'http://localhost').pathname);if(!file.startsWith(path.join(root,'dashboard'))||!fs.existsSync(file)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':'text/css');res.end(process.env.BASELINE_CAPTURE?require('node:child_process').execFileSync('git',['show','5020f50b6a4cab67df28c5ed4cb8d855cb5ddf45:dashboard/'+path.basename(file)],{cwd:root}):fs.readFileSync(file))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try{const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin===origin)return route.continue();if(url.hostname==='cdnjs.cloudflare.com'){const name=url.pathname.split('/').pop(),file=path.join(out,'vendor',name);if(fs.existsSync(file))return route.fulfill({body:fs.readFileSync(file),contentType:'text/javascript'})}if(url.hostname==='xrsilhiffjoulyoqhdmp.supabase.co'){const req=route.request(),method=req.method();let data=[];
if(url.pathname.endsWith('/match-report')){await sleep(briefDelay);if(briefFailure)return route.fulfill({status:503,body:'Synthetic brief failure'});return route.fulfill({json:{content:[{text:'Synthetic brief for '+JSON.parse(req.postData()).messages[0].content.match(/Alpha United|Gamma/)?.[0]}]}})}
if(url.pathname.includes('writing_lab_projects')){if(queueFailure&&method==='GET')return route.fulfill({status:503,body:'Synthetic queue failure'});if(method==='PATCH'){const id=url.searchParams.get('id')?.replace('eq.',''),body=JSON.parse(req.postData());patches.push({id,body});await sleep(patchDelay);if(patchFailure)return route.fulfill({status:503,body:'Synthetic offline save'});const p=projects.find(p=>p.id===id);Object.assign(p,body);data=[p]}else if(method==='POST'){posts++;const body=JSON.parse(req.postData()),p={...body,id:'00000000-0000-4000-8000-000000000003',scrape_status:'queued',workflow_status:'working'};projects.push(p);data=[p]}else{const gid=url.searchParams.get('game_id')?.replace('eq.','');data=gid?projects.filter(p=>p.game_id===gid):projects}}
else if(/events(_cup)?$/.test(url.pathname)){if(eventFailure)return route.fulfill({status:503,body:'Synthetic event failure'});if(eventEmpty)return route.fulfill({json:[]});data=url.searchParams.get('game_id')==='eq.101'?events:events.map(e=>({...e,game_id:'102',team:e.team==='Alpha United'?'Gamma':'Delta'}))}return route.fulfill({json:data})}return route.fulfill({status:200,body:'',contentType:'text/plain'})});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(origin+'/writing-lab.html?project='+projects[0].id);await page.waitForSelector('.pitch');await page.screenshot({path:path.join(out,process.env.BASELINE_CAPTURE?'before-writing-desktop-dark.png':'writing-desktop-dark.png'),fullPage:true});if(process.env.BASELINE_CAPTURE){await page.goto(origin+'/quick-ingest.html');await page.waitForSelector('.row');await page.screenshot({path:path.join(out,'before-quick-desktop-dark.png'),fullPage:true});console.log('Baseline screenshots captured with pinned source and synthetic data');return}check('Writing loads with meaningful content and controls',await page.locator('h1').innerText()==='The writing lab.' && await page.locator('button').count()>5);check('No initial page errors',errors.length===0);
await page.locator('#notes').fill('A recovered note');await page.evaluate(id=>openProject(id),projects[1].id);await page.locator('#notes').fill('B recovered note');await page.evaluate(id=>openProject(id),projects[0].id);check('A→B→A inside debounce preserves project-owned text',await page.locator('#notes').inputValue()==='A recovered note');await page.waitForTimeout(850);check('Saves target each immutable project ID',patches.some(p=>p.id===projects[0].id&&p.body.workspace_notes==='A recovered note')&&patches.some(p=>p.id===projects[1].id&&p.body.workspace_notes==='B recovered note'));
patchDelay=900;await page.locator('#notes').fill('A first revision');await page.waitForTimeout(730);await page.locator('#notes').fill('A newer revision');await page.evaluate(id=>openProject(id),projects[1].id);await page.waitForTimeout(1000);check('Late A save cannot switch active B',await page.evaluate(()=>CUR.game_id)==='102');await page.evaluate(id=>openProject(id),projects[0].id);check('Typing during save survives older response',await page.locator('#notes').inputValue()==='A newer revision');patchDelay=0;await page.waitForTimeout(900);
patchFailure=true;await page.locator('#notes').fill('Offline durable note');await page.waitForTimeout(850);check('Failed save announces local recovery',/retained locally/.test(await page.locator('#saveState').innerText()));await page.reload();await page.waitForSelector('#notes');check('Offline text survives reload',await page.locator('#notes').inputValue()==='Offline durable note');patchFailure=false;
await page.evaluate(id=>openProject(id),projects[1].id);projects[1].scrape_status='ready';await page.evaluate(()=>loadProjects(true));await page.waitForSelector('.pitch');check('Queued→ready fetches evidence without reopening',await page.evaluate(()=>EVENTS.length)===2);check('Fixture switch resets incompatible team',await page.evaluate(()=>TEAM)==='Gamma');
await page.locator('#notes').fill('Do not clobber me');await page.evaluate(()=>loadProjects(true));check('Metadata polling preserves focused dirty editor',await page.locator('#notes').inputValue()==='Do not clobber me'&&await page.locator('#notes').evaluate(e=>e===document.activeElement));
eventFailure=true;await page.evaluate(()=>renderCurrent(true));check('Evidence failure terminates loading with retry',/Evidence could not load/.test(await page.locator('#evidence').innerText()));eventFailure=false;await page.getByRole('button',{name:'Retry evidence',exact:true}).click();await page.waitForSelector('.pitch');
briefDelay=650;await page.evaluate(()=>{generateBrief(true)});await page.evaluate(id=>openProject(id),projects[0].id);await page.waitForTimeout(850);check('AI response remains attached to requesting workspace',await page.evaluate(()=>CUR.game_id)==='101' && !await page.evaluate(()=>CUR.editorial_brief));check('Background brief retained on its project',await page.evaluate(id=>PROJECTS.find(p=>p.id===id).editorial_brief,projects[1].id)==='Synthetic brief for Gamma');
await page.locator('[data-tab="draft"]').click();check('Desk tab URL persisted',new URL(page.url()).searchParams.get('tab')==='draft');await page.goBack();await page.waitForSelector('#notes');check('Back restores prior workspace tab',await page.locator('#notes').count()===1);
await page.locator('.viz-tools select').first().selectOption('Alpha United');await page.locator('details summary').last().click();check('Exact event trace available without hover',await page.locator('.trace').innerText().then(x=>x.includes('Alex Long-Name')&&x.includes('1')));
const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download evidence JSON'}).click();const file=await download;await file.saveAs(path.join(out,'synthetic-evidence.json'));const pack=JSON.parse(fs.readFileSync(path.join(out,'synthetic-evidence.json')));check('Downloaded evidence includes IDs, provenance and current scope',pack.events.length===2&&pack.context.game_id==='101'&&pack.context.filters.team==='Alpha United'&&pack.context.metric_version==='writing-events-v1');
const svgDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download plot SVG'}).click();await (await svgDownload).saveAs(path.join(out,'synthetic-plot.svg'));check('SVG includes portable provenance',fs.readFileSync(path.join(out,'synthetic-plot.svg'),'utf8').includes('<desc>'));
await savePlot(page,'png','writing-plot-dark.png');await savePlot(page,'pdf','writing-plot-dark.pdf');await page.evaluate(()=>toggleTheme());await savePlot(page,'png','writing-plot-light.png');await savePlot(page,'pdf','writing-plot-light.pdf');await page.evaluate(()=>toggleTheme());
eventEmpty=true;await page.evaluate(()=>renderCurrent(true));check('Empty evidence terminates in a factual empty state',/returned no records/.test(await page.locator('#evidence').innerText())&&await page.locator('#evidence .loading-lines').count()===0);eventEmpty=false;await page.evaluate(()=>renderCurrent(true));
check('Zero coordinates valid and missing coordinates excluded',await page.evaluate(()=>hasPoint({x:0,y:0})&&!hasPoint({x:null,y:2})));check('No pass denominator is missing not zero accuracy',await page.evaluate(()=>teamStats('Beta Town').acc===null));check('Heuristic checks retain exact supporting event IDs',await page.evaluate(()=>leadEvidence().find(x=>x.id==='story-1').event_ids.join(',')==='2'));
await page.evaluate(id=>openProject(id),projects[1].id);briefFailure=true;await page.evaluate(()=>generateBrief(true));await page.locator('[data-tab="brief"]').click();check('Failed regeneration preserves prior brief',/previous brief preserved/.test(await page.locator('#deskBody').innerText())&&/Synthetic brief for Gamma/.test(await page.locator('#deskBody').innerText()));briefFailure=false;
await page.locator('[data-tab="notes"]').click();await page.locator('#notes').fill('Changed after brief');await page.locator('[data-tab="brief"]').click();check('Brief stale state is identified after edits',/previous brief preserved|predates newer/.test(await page.locator('#deskBody').innerText()));await page.evaluate(id=>openProject(id),projects[0].id);
await page.locator('#matchUrl').fill('https://www.whoscored.com/Matches/101');await page.evaluate(()=>{const e={preventDefault(){}};createProject(e);createProject(e)});await page.waitForTimeout(200);check('Writing repeated existing-ID submit makes no POST',posts===0);await page.evaluate(()=>openProject('missing-id'));check('Invalid project clears prior match evidence',/Workspace unavailable/.test(await page.locator('#evidence').innerText())&&await page.locator('.pitch').count()===0);await page.evaluate(id=>openProject(id),projects[0].id);
for(const width of [320,375,390,640,768,1024,1440,1920]){await page.setViewportSize({width,height:900});check('Writing no page overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.evaluate(()=>toggleTheme());await page.setViewportSize({width:390,height:900});await page.screenshot({path:path.join(out,'writing-mobile-light.png'),fullPage:true});
await page.goto(origin+'/quick-ingest.html');await page.waitForSelector('.row');check('Quick ingest distinguishes raw-ready from publication',/publication not verified/.test(await page.locator('#rows').innerText()));await page.locator('#matchUrl').fill('https://www.whoscored.com/Matches/999');await page.evaluate(()=>{const e={preventDefault(){}};submit(e);submit(e)});await page.waitForTimeout(500);check('Duplicate in-flight submit produces one mocked POST',posts===1);await page.locator('#matchUrl').fill('https://www.whoscored.com/Matches/999');await page.getByRole('button',{name:'queue match'}).click();await page.waitForTimeout(300);check('Existing game does not create or retry automatically',posts===1&&/Existing match/.test(await page.locator('#feedback').innerText()));check('Result links preserve workspace ID',await page.locator('#feedback a').getAttribute('href')==='writing-lab.html?project=00000000-0000-4000-8000-000000000003');
for(const width of [320,375,390,640,768,1024,1440,1920]){await page.setViewportSize({width,height:900});check('Quick ingest no page overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.setViewportSize({width:390,height:900});await page.screenshot({path:path.join(out,'quick-mobile-light.png'),fullPage:true});check('No JavaScript page errors across workflows',errors.length===0);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,network:'All non-local requests intercepted; writes only synthetic in-memory records.'},null,2));
}finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
