const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('C:/Users/jbuck/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve('artifacts/ux-audit'),checks=[];function check(name,v){assert.ok(v,name);checks.push(name);console.log('PASS '+name)}
(async()=>{const b=await chromium.launch({channel:'msedge'});const c=await b.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
await c.route('**/*',r=>{let u=new URL(r.request().url());if(u.hostname==='127.0.0.1')return r.continue();const lib=u.pathname.split('/').pop();const local=path.resolve('artifacts/ux-audit-writing/vendor',lib);if(['html2canvas.min.js','jspdf.umd.min.js'].includes(lib)&&fs.existsSync(local))return r.fulfill({path:local,contentType:'application/javascript'});return r.abort();});const p=await c.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://127.0.0.1:8765/model-lab.html?tab=features');await p.waitForTimeout(250);
check('All coefficient rows visible',await p.evaluate(()=>document.querySelectorAll('.frow').length===D.coefficients.length));
check('Fixed coefficient scale declared',await p.locator('#featureRows').innerText().then(t=>t.includes('axis fixed')));
await p.getByRole('button',{name:'Explain a match',exact:true}).click();await p.selectOption('#matchSelect','1');const url=p.url();check('Stable fixture identity in URL',new URL(url).searchParams.has('game'));await p.reload();check('Fixture restored after reload',await p.locator('#matchSelect').inputValue()==='1');await p.getByRole('button',{name:'Feature evidence',exact:true}).click();await p.goBack();check('Tab restored by Back',await p.locator('#matches').evaluate(e=>e.classList.contains('on')));
await p.locator('#fsGoto button').click();check('All18 navigation links',await p.locator('#fsDestinationLinks a').count()===18);await p.keyboard.press('Escape');check('Navigation Escape returns focus',await p.locator('#fsGoto button').evaluate(e=>e===document.activeElement));
await p.goto('http://127.0.0.1:8765/model-review.html');await p.waitForTimeout(250);check('Forecast list no silent cap',await p.locator('.match').count()===await p.evaluate(()=>window.MODEL_REVIEW_DATA.predictions.length));check('Failed result feed has retry',await p.getByRole('button',{name:'Retry results'}).count()===1);
await p.goto('http://127.0.0.1:8765/market-values.html');await p.evaluate(()=>{ROWS=Array.from({length:230},(_,i)=>({id:i,name:'Player '+i,team:'Club '+i%20,league:'ENG-Premier League',role:'W',n90:i/20,value:(i+1)*100000,date:'2026-10-01'}));SEASON=ROWS.map(r=>({player_id:r.id,team:r.team}));ROWS.forEach(r=>TEAM_LEAGUE[r.team]=r.league);renderChart(ROWS);renderSquads(ROWS);renderLedger(ROWS)});check('All230 market chart records',await p.locator('#chart circle').count()===230);check('All20 clubs visible',await p.locator('.squad-row').count()===20);check('Square-root scale disclosed',await p.locator('#chart').innerText().then(t=>t.includes('square-root')));
await p.evaluate(()=>{const card=document.createElement('section');card.id='exportFixture';card.dataset.exportContext=JSON.stringify({subject:'Synthetic audit fixture',league:'Test league',sample:'50 rows',units:'per90',filters:'all rows',data_as_of:'2026-10-01'});card.innerHTML='<h2>Synthetic fifty-row ledger</h2><table style="width:100%"><thead><tr><th>Player</th><th>Value /90</th></tr></thead><tbody>'+Array.from({length:50},(_,i)=>'<tr style="height:38px"><td>Synthetic player '+(i+1)+'</td><td>'+i+'</td></tr>').join('')+'</tbody></table>';document.body.appendChild(card)});
for(const format of ['png','pdf']){const download=p.waitForEvent('download');await p.evaluate(f=>FutScoutExports.capture(document.getElementById('exportFixture'),f),format);const d=await download;await d.saveAs(path.join(out,'fifty-row-ledger.'+format));check('Real '+format+' download',fs.statSync(path.join(out,'fifty-row-ledger.'+format)).size>1000)}
check('No JavaScript exceptions',errors.length===0);fs.writeFileSync(path.join(out,'shared-tests.json'),JSON.stringify({checks,errors},null,2));await b.close()})().catch(e=>{console.error(e);process.exitCode=1});
