// Safe extracted-function regressions. No network, database writes or live data.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const path=require('path'),root=path.resolve(__dirname,'../..');
const match=fs.readFileSync(path.join(root,'dashboard/match.html'),'utf8');
const teams=fs.readFileSync(path.join(root,'dashboard/teams.html'),'utf8');
for(const [name,html] of [['match',match],['teams',teams]])for(const script of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(script[1],{filename:name});
function fn(source,name){const start=source.search(new RegExp('(?:async )?function '+name+'\\('));assert(start>=0,name);const body=source.indexOf('{',start);let depth=0,quote=null,line=false,block=false;for(let i=body;i<source.length;i++){const c=source[i],n=source[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&n==='/'){block=false;i++;}continue;}if(quote){if(c==='\\'){i++;continue;}if(c===quote)quote=null;continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='/'&&n==='/'){line=true;i++;continue;}if(c==='/'&&n==='*'){block=true;i++;continue;}if(c==='{')depth++;if(c==='}'&&!--depth)return source.slice(start,i+1);}throw Error(name);}
const state={team:'__ALL__',viewTeam:'Seattle',matchTeams:['Seattle','Kansas'],selMatch:1,matches:[{game_id:1,home_team:'Seattle Sounders FC',away_team:'Kansas City'}],events:[],carries:[],periods:new Set(['1']),outcomes:new Set(['Successful']),posGroups:new Set(),timeFilter:{s:10,e:20},selPlayer:null,playerPos:{}};
const context=vm.createContext({S:state,Set,Number,Math,TEAMS:{__ALL__:{name:'__ALL__'}},TEAM_VIZ:new Set(['shape','dominance','formation','network','combos','passflow','xt_carry']),VIZ_LABELS:{network:'Network',passes:'Passes'},evName:n=>({'Seattle Sounders FC':'Seattle','Kansas City':'Kansas'}[n]||n),DEF_TYPES:['Tackle'],isProgPass:e=>e.end_x-e.x>20});
for(const name of ['T','VT','posToGroup','passesPosFilter','getFiltered','getKeyPasses','buildPanelTitle','computePlayerStats','lastName'])vm.runInContext(fn(match,name),context);
state.events=[{team:'Seattle',player:'Alex Roldan',type:'Pass',period:1,minute:12,second:0,outcome_type:'Successful',x:30,y:50,end_x:90,end_y:50},{team:'Seattle',player:'Cristian Roldan',type:'SavedShot',is_shot:true,period:1,minute:12,second:2,outcome_type:'Successful',x:90,y:50},{team:'Kansas',player:'Opponent',type:'Pass',period:1,minute:13,outcome_type:'Successful',x:30,y:50,end_x:60,end_y:50},{team:'Seattle',player:'Alex Roldan',type:'Pass',period:2,minute:60,outcome_type:'Successful',x:30,y:50,end_x:90,end_y:50}];
assert.equal(context.getFiltered('shape').length,2);assert.equal(context.getFiltered('dominance').length,3);
for(const plot of ['passes','progressive','final_third','zone14','box_passes','keypasses','network','combos','shots','heatmap','xt','xt_carry','defensive','pressure','shape','formation','dominance'])assert(context.getFiltered(plot).every(e=>e.period===1&&e.minute>=10&&e.minute<20),plot);
assert.equal(context.getKeyPasses().length,1);state.outcomes=new Set(['Unsuccessful']);assert.equal(context.getKeyPasses().length,0);state.outcomes=new Set(['Successful']);
state.selPlayer='Alex Roldan';assert.match(context.buildPanelTitle('network'),/^Seattle Network.*Kansas City.*H$/);assert.equal(context.computePlayerStats('Alex Roldan').Passes,1);assert.equal(context.lastName('Alex Roldan'),'Alex Roldan');
state.viewTeam='Kansas';assert.equal(context.computePlayerStats('Opponent').Passes,1);assert.match(context.buildPanelTitle('network'),/^Kansas Network.*Seattle Sounders FC.*A$/);
const teamContext=vm.createContext({Number,Math,SEL:'A',TAB:'Maps',LG:'ALL',MP:{},RKT:{},LM:{},teamViewRevision:1,esc:String,SEQ_GROUPS:[{g:'Group',m:[['metric','Metric',1,'']]}],tname:x=>x});
for(const name of ['teamRequest','displayMetric','seqRadar','zFmt'])vm.runInContext(fn(teams,name),teamContext);
const current=teamContext.teamRequest();assert(current());teamContext.SEL='B';assert(!current());teamContext.SEL='A';teamContext.teamViewRevision++;assert(!current());
assert.equal(teamContext.displayMetric(null),'—');assert.equal(teamContext.displayMetric(0),'0.0');assert.match(teamContext.seqRadar({team:'A'},{metric:null},{metric:null}),/Comparison unavailable/);
assert(!teams.includes('a.xg||0.04'));assert(teams.includes("TFIXTURES.forEach"));
const shots=[{game_id:1,team:'B',xg:0},{game_id:1,team:'B',xg:null},{game_id:1,team:'B',xg:.3}],fixtures=[{game_id:1}];const conceded=shots.filter(s=>fixtures.some(f=>f.game_id===s.game_id)&&s.team!=='A');assert.equal(conceded.length,3);assert.equal(conceded.filter(s=>s.xg!=null).reduce((n,s)=>n+s.xg,0),.3);
state.viewTeam='Seattle';state.selPlayer='Selected';state.periods=new Set(['1']);state.outcomes=new Set(['Successful']);state.timeFilter={s:10,e:20};state.events=[];
for(const player of ['Selected','Other'])for(const minute of [12,30])for(const period of [1,2])for(const outcome_type of ['Successful','Unsuccessful'])for(const type of ['Pass','SavedShot','Tackle'])for(const end_x of [75,90])state.events.push({team:'Seattle',player,minute,period,outcome_type,type,is_shot:type==='SavedShot',is_open_play:true,x:20,y:50,end_x,end_y:50});
state.carries=[{team:'Seattle',minute:12,period:1},{team:'Seattle',minute:30,period:1},{team:'Seattle',minute:12,period:2}];
const unsupported=new Set(['shape','dominance','formation','network','combos','xt_carry']);
for(const plot of ['passes','progressive','final_third','zone14','box_passes','keypasses','network','combos','shots','heatmap','xt','xt_carry','defensive','pressure','shape','formation','dominance']){const rows=context.getFiltered(plot);assert(rows.length>0,plot+' non-vacuous');assert(rows.every(e=>e.period===1&&e.minute===12),plot+' period/window');if(plot!=='xt_carry')assert(rows.every(e=>e.outcome_type==='Successful'),plot+' outcome');if(!unsupported.has(plot))assert(rows.every(e=>e.player==='Selected'),plot+' player');else if(plot!=='xt_carry')assert(rows.some(e=>e.player==='Other'),plot+' declared team scope');}
console.log('PASS: syntax; non-vacuous all17 selected-player/period/window/outcome matrix including explicit unsupported team/carry scope; identity and alias; stale requests; xG missing/zero coverage.');
