
insert into public.metric_defs (key,label,grp,unit,higher_is_better,definition,calc,grp_order,sort_order) values
('seq_passes_seq','Passes per possession','Possession',null,true,
 'Average number of passes in an unbroken spell of possession. The league averages 3.61, and the spread between sides is narrower than intuition suggests.',
 'Mean n_pass across open-play sequences.',13,1),
('seq_seconds_seq','Seconds per possession','Possession','s',true,
 'How long a side keeps the ball once it wins it. League average 10.2 seconds. Long spells indicate patience, not necessarily control.',
 'Mean duration across open-play sequences.',13,2),
('seq_xt_seq','xT per possession','Possession',null,true,
 'Threat generated per spell of possession. The single best summary of whether having the ball is worth anything. League average 0.0164.',
 'Mean xt_sum across open-play sequences.',13,3),
('seq_ends_in_shot','Possessions ending in a shot','Possession','%',true,
 'The conversion of possession into attempts. League average 9.2%. High possession with a low figure here is the signature of sterile control.',
 'Share of open-play sequences where ended_shot is true.',13,4),
('seq_low_build','Building from deep','Possession','%',true,
 'Share of possessions starting in the defensive third. High values mean a side that plays out rather than winning the ball high.',
 'Share of sequences with start_x below 33.3.',13,5),
('seq_high_build','Winning it high','Possession','%',true,
 'Share of possessions beginning in the attacking half — a proxy for pressing success rather than a pressing metric itself.',
 'Share of sequences with start_x at or above 50.',13,6),
('seq_long_ball','Going long','Possession','%',false,
 'Share of possessions containing a long or lofted pass. Neither good nor bad in isolation; read it against whether the route produces shots.',
 'Share of sequences flagged long_ball.',13,7),
('seq_switches','Switching play','Possession','%',true,
 'Share of possessions containing a switch across the pitch. Indicates a side that manipulates a block rather than attacking one side.',
 'Share of sequences flagged has_switch.',13,8),
('seq_finds_central','Progressing centrally','Possession','%',true,
 'Share of possessions where the first attacking-third entry arrives through the middle. Miami lead the league at 34.9%.',
 'Share of sequences flagged finds_central.',13,9),
('seq_finds_wide','Progressing wide','Possession','%',true,
 'Share of possessions where the first attacking-third entry arrives in a wide channel. The counterpart to central progression.',
 'Share of sequences flagged finds_wide.',13,10),
('seq_directness','Possession directness','Possession',null,true,
 'Net upfield progress as a share of total distance the ball travelled. 1.0 would be a straight line at goal; near zero is sideways circulation.',
 '(end_x - start_x) / (mean pass length x pass count), clamped to -1..1.',13,11),
('seq_state_swing','Directness swing by game state','Possession',null,true,
 'How much a side''s directness changes between losing and winning. A large swing marks a reactive side; near zero marks a settled identity. Neither is inherently better.',
 'Directness when losing minus directness when winning.',13,12),
('seq_route_productivity','Route productivity','Possession',null,true,
 'How often a given route produces a shot, measured against the league average for that same route. Separates what a side does from whether it works.',
 'Shot-ending share per route, z-scored within league.',13,13),

('role_initiator','Initiator','Chain roles','%',true,
 'Share of a player''s involvements that begin a possession. High values mark the player a side builds from, typically a defender or deep midfielder.',
 'Share of involvements at position 1 in the chain.',14,1),
('role_bridge','Third-man bridge','Chain roles','%',true,
 'Mid-chain passes that advance the ball a full third. The connector between build-up and attack — De Paul and Herrera both lead on this.',
 'Share of involvements that are mid-chain passes crossing a third boundary.',14,2),
('role_progressor','Progressor','Chain roles','%',true,
 'Share of involvements that move the ball at least 10 units upfield. The most straightforward measure of forward intent.',
 'Share of involvements that are progressive passes.',14,3),
('role_carrier','Carrier','Chain roles','%',true,
 'Ball progression under the player''s own power rather than by pass. Derived, because the event feed has no explicit carry event.',
 'Consecutive same-player forward touches.',14,4),
('role_vertical','Vertical passer','Chain roles','%',true,
 'Forward passes played straight rather than diagonally. Marks a player who plays through a block rather than around it.',
 'Forward passes with small lateral deviation.',14,5),
('role_support','Diagonal support','Chain roles','%',true,
 'Passes made or received at roughly 45 degrees. The angle of a player offering himself as an option rather than receiving flat.',
 'Passes in the 35-55 degree band, made or received.',14,6),
('role_individual','1v1 dribbler','Chain roles','%',true,
 'Share of involvements that are take-ons. Distinct from carrying: this is beating a man, not covering ground.',
 'Share of involvements that are TakeOn events.',14,7),
('role_creator','Creator','Chain roles','%',true,
 'Passes immediately preceding a shot. The conventional key pass, expressed as a share of everything the player does.',
 'Share of involvements directly followed by a shot.',14,8),
('role_box_threat','Box threat','Chain roles','%',true,
 'Share of involvements occurring inside the penalty area. Separates a penalty-box striker from a forward who drops in.',
 'Share of involvements with x at or above 83 in the central channel.',14,9),
('role_finisher','Finisher','Chain roles','%',true,
 'Share of involvements that are shots. Messi reads highest among attacking midfielders, reflecting a role that now ends moves rather than building them.',
 'Share of involvements that are shot events.',14,10),
('role_controller','Tempo','Chain roles','s',true,
 'Average seconds between receiving and releasing. Neither high nor low is better: it separates a player who slows a game from one who moves it on.',
 'Mean hold time, whole-second resolution.',14,11),
('chain_early_shot','Early involvement in shot chains','Chain roles',null,true,
 'How often a player appears three or more actions before a shot. Credits the pass that starts a move rather than the one that finishes it. Contaminated by teammate quality.',
 'Involvements at least 3 steps from the end of a shot-ending sequence, per 90.',14,12)
on conflict (key) do update set label=excluded.label, grp=excluded.grp, definition=excluded.definition,
  calc=excluded.calc, grp_order=excluded.grp_order, sort_order=excluded.sort_order,
  unit=excluded.unit, higher_is_better=excluded.higher_is_better;
